### ISSUE TITLE
Custom field is replaced by library default

### ISSUE THREAD

**Issue by Sonosus** [holmesrichards/mdbom#2]
When I set a custom 'Description' field in Tools>Edit Symbol fields, my custom text is overwritten by the description in the library symbol (I think).
Input: 
![image](https://user-images.githubusercontent.com/67963676/166438239-86b1608f-d4dd-44a9-b876-ee1c881fd96f.png)
Output (preview in Dillinger):
![image](https://user-images.githubusercontent.com/67963676/166438340-f958865b-973a-486a-9d7d-a270653be178.png)

Is there a way of disabling this within the plugin, or will I have to copy all the symbols to my own library and edit them to add custom descriptions?

**Comment by holmesrichards** [comment]
The Description entry in the library symbol is stored separately from the Fields:
![bitmap](https://user-images.githubusercontent.com/56895621/166445672-15e360f9-33c8-43aa-8753-d2ce56fe5f3b.png)
In the API component.getDescription() returns that while component.getField(field) returns the named field. So for what you want to do it may be (I haven't tried it) as simple as replacing c.getDescription() in the BOM script with c.getField("Description")... Well, no, because that would return empty on symbols where you haven't added your own description, so you'd probably want to do something like

```
d = c.getField("Description")
if d=="":
    d = c.getDescription()
rows.append([refs, str(len(group)), c.getValue(), d)
```
Does that work? It might be a useful mod now that I think about it.

**Comment by Sonosus** [comment]
It works perfectly. I added a PR.

**Comment by holmesrichards** [comment]
Good. I eventually realized you can use the Edit Symbol... button in the symbol properties pane to change the description for a particular instance of a symbol, but adding a Description field in that pane may be more convenient. Fewer clicks and it doesn't involve opening the symbol editor.
